### get books by author: /{author}/{limit}/{page}
GET {{backend}}/books_by_author/Роулинг/5/1
Accept: application/json

### get books by author, no params: /{author}
GET {{backend}}/books_by_author/доСтоевсКиЙ
Accept: application/json

### get books by author, no author for search
GET {{backend}}/books_by_author/
Accept: application/json