### get books list: /{limit}/{page}
GET {{backend}}/books/2/1
Accept: application/json

### get books list, invalid page
GET {{backend}}/books/1/0
Accept: application/json

### get books list, no params
GET {{backend}}/books/
Accept: application/json